// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"time"

	"github.com/google/uuid"
)

type Note struct {
	NoteID    uuid.UUID
	DailyNote string
	CreatedAt time.Time
	UpdatedAt time.Time
}
