// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Note struct {
	NoteID    uuid.UUID
	DailyNote string
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
}

type RefreshToken struct {
	Token     string
	CreatedAt time.Time
	UpdatedAt time.Time
	ExpiresAt time.Time
	RevokedAt sql.NullTime
	Userid    uuid.UUID
}

type User struct {
	ID           uuid.UUID
	CreatedAt    time.Time
	Email        string
	PasswordHash string
}
