// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notes.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createNote = `-- name: CreateNote :one
INSERT INTO Notes (note_id, user_id, daily_note, created_at, updated_at) values (
        gen_random_uuid(), $1, $2, NOW(), NOW()
)
RETURNING note_id, daily_note, created_at, updated_at, user_id
`

type CreateNoteParams struct {
	UserID    uuid.UUID
	DailyNote string
}

func (q *Queries) CreateNote(ctx context.Context, arg CreateNoteParams) (Note, error) {
	row := q.db.QueryRowContext(ctx, createNote, arg.UserID, arg.DailyNote)
	var i Note
	err := row.Scan(
		&i.NoteID,
		&i.DailyNote,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const deleteNote = `-- name: DeleteNote :exec
DELETE FROM Notes
where note_id = $1
`

func (q *Queries) DeleteNote(ctx context.Context, noteID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteNote, noteID)
	return err
}

const getAllNotes = `-- name: GetAllNotes :many
SELECT note_id, daily_note, created_at, updated_at, user_id FROM Notes where user_id = $1
`

func (q *Queries) GetAllNotes(ctx context.Context, userID uuid.UUID) ([]Note, error) {
	rows, err := q.db.QueryContext(ctx, getAllNotes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Note
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.NoteID,
			&i.DailyNote,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSortedNotes = `-- name: GetSortedNotes :many
SELECT note_id, daily_note, created_at, updated_at, user_id FROM Notes WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetSortedNotes(ctx context.Context, userID uuid.UUID) ([]Note, error) {
	rows, err := q.db.QueryContext(ctx, getSortedNotes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Note
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.NoteID,
			&i.DailyNote,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readNote = `-- name: ReadNote :one
SELECT note_id, daily_note, created_at, updated_at, user_id FROM Notes WHERE note_id = $1
`

func (q *Queries) ReadNote(ctx context.Context, noteID uuid.UUID) (Note, error) {
	row := q.db.QueryRowContext(ctx, readNote, noteID)
	var i Note
	err := row.Scan(
		&i.NoteID,
		&i.DailyNote,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const updateNote = `-- name: UpdateNote :one
UPDATE Notes
SET daily_note = $2, updated_at = NOW()
where note_id = $1
RETURNING note_id, daily_note, created_at, updated_at, user_id
`

type UpdateNoteParams struct {
	NoteID    uuid.UUID
	DailyNote string
}

func (q *Queries) UpdateNote(ctx context.Context, arg UpdateNoteParams) (Note, error) {
	row := q.db.QueryRowContext(ctx, updateNote, arg.NoteID, arg.DailyNote)
	var i Note
	err := row.Scan(
		&i.NoteID,
		&i.DailyNote,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}
