// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const increaseNoteCount = `-- name: IncreaseNoteCount :exec
UPDATE Users SET today_count = today_count + 1, total_notes = total_notes + 1 where id = $1
`

func (q *Queries) IncreaseNoteCount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, increaseNoteCount, id)
	return err
}

const registerUser = `-- name: RegisterUser :one
INSERT INTO Users (id, created_at, username, email, password_hash) values (
    gen_random_uuid(), NOW(), $1, $2, $3
)
RETURNING id, created_at, email, password_hash, username, current_streak, max_streak, total_notes, today_count
`

type RegisterUserParams struct {
	Username     string
	Email        string
	PasswordHash string
}

func (q *Queries) RegisterUser(ctx context.Context, arg RegisterUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, registerUser, arg.Username, arg.Email, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Email,
		&i.PasswordHash,
		&i.Username,
		&i.CurrentStreak,
		&i.MaxStreak,
		&i.TotalNotes,
		&i.TodayCount,
	)
	return i, err
}

const resetCurrentStreak = `-- name: ResetCurrentStreak :exec
UPDATE Users SET current_streak = 1 WHERE id = $1
`

func (q *Queries) ResetCurrentStreak(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, resetCurrentStreak, id)
	return err
}

const resetDailyCount = `-- name: ResetDailyCount :exec
UPDATE Users SET today_count = 0
`

func (q *Queries) ResetDailyCount(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetDailyCount)
	return err
}

const searchUserByEmail = `-- name: SearchUserByEmail :one
SELECT id, created_at, email, password_hash, username, current_streak, max_streak, total_notes, today_count FROM Users where email = $1
`

func (q *Queries) SearchUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, searchUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Email,
		&i.PasswordHash,
		&i.Username,
		&i.CurrentStreak,
		&i.MaxStreak,
		&i.TotalNotes,
		&i.TodayCount,
	)
	return i, err
}

const searchUserByUserName = `-- name: SearchUserByUserName :one
SELECT id, created_at, email, password_hash, username, current_streak, max_streak, total_notes, today_count FROM Users where username = $1
`

func (q *Queries) SearchUserByUserName(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, searchUserByUserName, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Email,
		&i.PasswordHash,
		&i.Username,
		&i.CurrentStreak,
		&i.MaxStreak,
		&i.TotalNotes,
		&i.TodayCount,
	)
	return i, err
}

const updateStreak = `-- name: UpdateStreak :exec
UPDATE Users SET current_streak = current_streak + 1, max_streak = GREATEST(max_streak, current_streak + 1) WHERE id = $1
`

func (q *Queries) UpdateStreak(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, updateStreak, id)
	return err
}
