// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package database

import (
	"context"
)

const registerUser = `-- name: RegisterUser :one
INSERT INTO Users (id, created_at, email, password_hash) values (
    get_random_uuid(), NOW(), $1, $2
)
RETURNING id, created_at, email, password_hash
`

type RegisterUserParams struct {
	Email        string
	PasswordHash string
}

func (q *Queries) RegisterUser(ctx context.Context, arg RegisterUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, registerUser, arg.Email, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Email,
		&i.PasswordHash,
	)
	return i, err
}

const searchUserByEmail = `-- name: SearchUserByEmail :one
SELECT id, created_at, email, password_hash FROM Users where email = $1
`

func (q *Queries) SearchUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, searchUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Email,
		&i.PasswordHash,
	)
	return i, err
}
